### ISSUE TITLE
Error with else and if statement

### ISSUE THREAD

**Issue by Smeds** [snakemake/snakefmt#91]
Hi!

Snakefmt failes while parsing my workflow:

```
 if config["programs"]["Duplicates"] == "fgbio":
    include: "../rules/Alignment/fgbio.smk"
else:
    if config["programs"]["markduplicate"] == "GPU":
        include: "../rules/Alignment/GPU_alignment.smk"
    else:
        include: "../rules/Alignment/bwa-mem.smk"
        include: "../rules/Alignment/MarkDuplicates.smk"
```

with the following message

> [ERROR] In file "src/Snakemake/workflow/Twist_DNA_workflow.smk":  'InvalidPython: Got error:
> ```
> Cannot parse: 1:2: if:
> ```
> while formatting code with black.'
> [INFO] In file "src/Snakemake/workflow/Twist_DNA_workflow.smk":  1 file(s) raised parsing errors

running black manually gives me no errors. 

if I remove the if statement after else I get no errors.

```
if config["programs"]["Duplicates"] == "fgbio":
    include: "../rules/Alignment/fgbio.smk"
else:
    include: "../rules/Alignment/GPU_alignment.smk"
```

**Comment by Smeds** [comment]
if I have an include between 'else' and 'if' it can parse the workflow.

```
if config["programs"]["Duplicates"] == "fgbio":
    include: "../rules/Alignment/fgbio.smk"
else:
    include: "../rules/Alignment/GPU_alignment.smk"
    if config["programs"]["markduplicate"] == "GPU":
        include: "../rules/Alignment/GPU_alignment.smk"
    else:
        include: "../rules/Alignment/bwa-mem.smk"
        include: "../rules/Alignment/MarkDuplicates.smk"
```
