### ISSUE TITLE
newlines formatting

### ISSUE THREAD

**Issue by Smeds** [snakemake/snakefmt#93]
I have some questions about the number of new lines required by snakefmt

Example
```
if config["programs"]["Duplicates"] == "fgbio":

    include: "../rules/Alignment/fgbio.smk"
    print("Test")
    include: "../rules/SNV/freebayes.smk"
else:
    if config["programs"]["markduplicate"] == "GPU":

        include: "../rules/Alignment/GPU_alignment.smk"
    else:

        include: "../rules/Alignment/bwa-mem.smk"
        include: "../rules/Alignment/MarkDuplicates.smk"
include: "../rules/SNV/freebayes.smk"
include: "../rules/SNV/mutect2.smk"
```

would change to

```
  if config["programs"]["Duplicates"] == "fgbio":
  
      include: "../rules/Alignment/fgbio.smk"
 
 
 print("Test")
 
      include: "../rules/SNV/freebayes.smk"
 
 
  else:
      if config["programs"]["markduplicate"] == "GPU":
  
          include: "../rules/Alignment/GPU_alignment.smk"
 
 
      else:
  
          include: "../rules/Alignment/bwa-mem.smk"
 
          include: "../rules/Alignment/MarkDuplicates.smk"
  include: "../rules/SNV/freebayes.smk"
  include: "../rules/SNV/mutect2.smk"

```
How many new lines are required seems to be a bit inconsistent and sometimes a bit excessive, atleast for if/else code blocks:
1. Why is 2 new lines added after an "include" inside a if/else code block?
2. Why is the indentation removed for print("Test") and two new lines added?
3. Why is a new line introduced  between the include statements in the last else block but not for the two last lines?
4. Shouldn't there be new lines after the last "else" code block?

**Comment by bricoletc** [comment]
Hi again @Smeds, these are good points.
1. We decided to separate distinct snakemake keywords by two newlines, but perhaps inside such a block should be one.
2. Is definitely a bug
3. This is deliberate (I'll dig into why) but could conceivably be changed
4. I agree

**Comment by bricoletc** [comment]
Ok, https://github.com/snakemake/snakefmt/commit/6fb340014703244adec393ed0e788d8c737660f6 implements your points 2, 3, and 4. (digging into 3, can't find a good justification for it).

For point 1, we are actually mirroring black:
```
if p:

    class p:
        elem1 = 2


else:

    class a:
        pass
```
And I find this readable so will keep it. 

If (for readability) you place your `print` statement before the `include`s, it will now look like:

```
if config["programs"]["Duplicates"] == "fgbio":

    print("Test")

    include: "../rules/Alignment/fgbio.smk"
    include: "../rules/SNV/freebayes.smk"


else:
    if config["programs"]["markduplicate"] == "GPU":

        include: "../rules/Alignment/GPU_alignment.smk"


    else:

        include: "../rules/Alignment/bwa-mem.smk"
        include: "../rules/Alignment/MarkDuplicates.smk"


include: "../rules/SNV/freebayes.smk"
include: "../rules/SNV/mutect2.smk"
```
What do you think @Smeds ?
